### ISSUE TITLE
[Feature]: Implement times parser

### ISSUE THREAD

**Issue by bobjoe12131** [patrik-kuehl/pickle#82]
### Proposal

The `times` parser applies a parser a given amount of times.

**Use Case:** For a specific length of tokens.
**Alternative:** `times(par, 3)` expands to `par |> then(par) |> then(par)`

**Type Signature:**
```gleam
pub fn times(
  parser: Parser(a, a, b),
  parse_times: Int,
) -> Parser(a, a, b)
```

**Implementation:**
```gleam
pub fn times(
  parser: Parser(a, a, b),
  parse_times: Int,
) -> Parser(a, a, b) {
  case parse_times {
    _ if parse_times <= 0 -> fn(parsed) { Ok(parsed) }
    1 -> parser
    _ -> then(parser, times(parser, parse_times - 1))
  }
}
```

**Test**
```gleam
pub fn pickle_times_test() {
  let empty = #("", "")
  let parsable = "ANYREST"
  let parser =
    pickle.any(fn(a: #(String, String), str) { #(a.0 <> str, a.1) })
    |> pickle.times(3)
    |> pickle.then(
      pickle.until(
        "",
        pickle.any(string.append),
        pickle.eof(),
        fn(a: #(String, String), str) { #(a.0, a.1 <> str) },
      ),
    )
  let result = pickle.parse(parsable, empty, parser)
  result |> should.be_ok() |> should.equal(#("ANY", "REST"))
}
```

**Comment by patrik-kuehl** [comment]
Thanks for your proposal, and especially for such a detailed one like yours.

The suggestion for the implementation already goes in a direction I'd have favored anyway (no panicking, just ignoring invalid counts, just as `one_of` results in a NOP when being provided an empty list).

To be honest, as of now my focus is to simplify some other areas of Pickle as this library has become more self-sufficient, so a lot of the early internal parsers (especially the ones used by the integer parsers) can be simplified by utilizing `many1`.

I wasn't planning to add further parsers before this is finished, but given the usefulness of this parser, I'll make sure this parser is part of the next release.

I will need it anyway when I start to implement the integer parsers that expect a specific amount of digits.
