### ISSUE TITLE
[Feature]: Implement digit parser

### ISSUE THREAD

**Issue by patrik-kuehl** [patrik-kuehl/pickle#89]
### Proposal

The `pickle/digit` parser parses a single decimal digit.

**Comment by bobjoe12131** [comment]
Will it parse only one of those described, or will it take a number base?

**Comment by patrik-kuehl** [comment]
It won't have a parameter for specifying the base, as there will be dedicated parsers for this like `pickle/binary_digit`.

It tries to parse a token as a digit of a specific numeral system in order until it succeeds, failing otherwise.

The implementation most likely will look like this:

```gleam
pub fn digit(mapper: fn(a, Int) -> a) -> Parser(a, a, b) {
  one_of([
    decimal_digit(mapper),
    binary_digit(mapper),
    hexadecimal_digit(mapper),
    octal_digit(mapper),
  ])
}
```

`pickle/integer` does the same, besides also looking for prefixes that imply a specific numeral system.

Documenting this will also become a high priority after refactoring the internal implementation of the integer parsers, as consumers need to take a look at the implementation to know in what order numeral systems inside `pickle/integer` (and `pickle/digit` eventually) are tried.

Adding, detailing, and enhancing documentation will play a major role when Pickle is heading toward its first major release.

**Comment by bobjoe12131** [comment]
Sounds difficult without number base context. 
Take this (dec | bin | hex | oct) number 10010101.
Turn it into decimal and it is (10010101 | 149 | 268501249 | 2101313)
Matching: 
binary first ->  no more numbers with just 0|1 in other bases.
others first -> no binary

**Comment by patrik-kuehl** [comment]
The ambiguity of `pickle/integer`, and `pickle/digit` eventually, can indeed result in unexpected behavior due to the example you provided. I only introduced them to have some sort of catch-all parsers for all common numeral systems, being aware of the risk you also showed. Using other parsers like `pickle/binary_integer` can be used to avoid this problem.

If I understand you correctly, you don't see a benefit in providing these catch-all parsers that handle different numeral systems at once?

Looking at [Combine](https://hexdocs.pm/combine/Combine.Parsers.Text.html) where I took some inspiration from, this parser combinator only provides parsers that can only handle a specific base. Is this something you would have expected instead?

So `pickle/integer` and `pickle/digit` become limited to base 10, while the other prefixed parsers handle other numeral systems.

I have no problem reconsidering my choice here, as I'm always open to design discussions.

**Comment by bobjoe12131** [comment]
Yes. The unexpected behavior would eventually happen. It would be better to have the explicit base parsers and/or have it take a number for the base.

**Comment by patrik-kuehl** [comment]
> Maybe you can prefix the digit function you originally made the feature issue about with unsafe if you really want it.

Won‘t be necessary, I agree with your reasoning.

I will go the route Combine had taken by letting  the unprefixed parsers (**digit** and **integer**) only handle base 10, the prefixed ones the respective numeral system mentioned in the prefix.

I will update the issues accordingly this week. This approach also results in a even simpler implementation of the integer parsers since I don‘t have to look for numeral system prefixes any longer.
